### PR TITLE
Gave the Autovalues section some readability

### PR DESCRIPTION
**Pull request by jklw10**
Sectioned auto values into General, Armor, Weapons, Tools and Crafting.
This way finding the config you're looking for is just a tad easier.

### CODE REVIEW

**Comment by jklw10** [comment]
output looks like this 
image

**Review by didis54 — CHANGES_REQUESTED** [review]
Only for the readability of the code:
You are missing line breaks (1589, 1557, 1533, 1531, ...)
Too many line breaks (1487-1489)
Try to make it as readable and clean as what's above

**Comment by jklw10** [comment]
ah ok sorry i'm a bit unused to working on projects.

**Comment by didis54** [comment]
As long that you test all your change before submitting it, keep it clean, and review it.
Then there is no issue
Just don't submit changes that you didn't tested before, because you will just end up giving more work to Harm which he does not need

**Comment by jklw10** [comment]
ah true. i have a change to how combat level requirements are calculated coming so i'll have to finish that before testing my changes. or i could just create a new pull request for both of these changes in 1 go?

**Comment by didis54** [comment]
Separate your changes and put description to why you are proposing those change and what value they can give to PMMO

**Comment by jklw10** [comment]
so i should remove the changes i did in this pull reguest from the other pull request or just wait until this one is pulled to create that one?

**Review by didis54 — CHANGES_REQUESTED** [review]
Still missing some line break before; builder.pop();
(like line 1484 as an example)
Please review all of what you did and keep everything as clean as it was before

**Comment by didis54** [comment]
Im not sure how Github handle changes on the same file if it hasn't been applied yet, so i would suggest to wait for this one to be approved (or rejected)

**Comment by jklw10** [comment]
hmm. is there a channel on the discord where this could be discussed?
i don't like the fact i can't be pinged/ can't ping. also i have some questions not related to this pull req

**Comment by didis54** [comment]
You have plenty of channel related to pmmo ^^, just don't ping Harm for such thing (you can ping me I don't care, but i cant
 help you that much)

image

**Comment by Harmonised7** [comment]
The config has a very specific layer system for a reason. Otherwise, the generator for https://harmonised7.github.io/minecraft/pmmo/Config.html would break. I cannot accept this. If you are unhappy with this, please consider that you've never asked if this is okay to do.

**Pull request closed without merging**
